# Generated by Django 2.2.1 on 2019-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentID', models.CharField(max_length=120)),
                ('OrgID', models.CharField(max_length=120)),
                ('Category', models.CharField(max_length=300)),
                ('Question', models.CharField(max_length=500)),
                ('Rating', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgID', models.CharField(max_length=120)),
                ('OrgName', models.CharField(max_length=120)),
                ('OrgLocation', models.CharField(max_length=120)),
                ('OrgSize', models.CharField(max_length=120)),
                ('OrgDomain', models.CharField(max_length=120)),
            ],
        ),
    ]
